Actor.create!([
  {first_name: "Nathan", last_name: "Fillion", known_for: "Firefly"},
  {first_name: "Sarah", last_name: "Michelle", known_for: "Buffy"},
  {first_name: "Allison", last_name: "Hannigan", known_for: "Buffy"},
  {first_name: "Robert", last_name: "Downey Jr.", known_for: "Iron Man"},
  {first_name: "Brad", last_name: "Pitt", known_for: "Fight Club"},
  {first_name: "Johnny", last_name: "Deep", known_for: "Pirates of the Caribean"},
  {first_name: "Will", last_name: "Smith", known_for: "Independence Day"},
  {first_name: "Samuel", last_name: "Jackson", known_for: "Pulp Fiction"},
  {first_name: "Christian", last_name: "Bale", known_for: "The Dark Knight"},
  {first_name: "Harrison", last_name: "Ford", known_for: "Indiana Jones"},
  {first_name: "Mark", last_name: "Hamill", known_for: "Star Wars"},
  {first_name: "Bruce", last_name: "Willis", known_for: "Die Hard"},
  {first_name: "Jason", last_name: "Bateman", known_for: "Arrested Development"},
  {first_name: "Will", last_name: "Arnett", known_for: "Bojack Horseman"},
  {first_name: "Amy", last_name: "Poehler", known_for: "Parks and Recreation"},
  {first_name: "Michael", last_name: "Cera", known_for: "Superbad"},
  {first_name: "Angelique", last_name: "Sporer", known_for: "Action Cousins"},
  {first_name: "Geralyn", last_name: "Corwin", known_for: "The Gypsy Who Fell to Earth"},
  {first_name: "Candance", last_name: "Shanahan", known_for: "The Action Thief from Outer Space"},
  {first_name: "Drew", last_name: "Armstrong", known_for: "The Cat Who Fell to Earth"},
  {first_name: "Deana", last_name: "Spinka", known_for: "A Fistful of Bloody Clash"},
  {first_name: "Mckinley", last_name: "Mann", known_for: "Blonde Rain: The Saul Rohan Story"},
  {first_name: "Marlyn", last_name: "Beatty", known_for: "Red Tears"},
  {first_name: "Gwenn", last_name: "Crona", known_for: "Fake Gypsy"},
  {first_name: "Nora", last_name: "Nikolaus", known_for: "The Ninjas with a Thousand Faces"},
  {first_name: "Treva", last_name: "Abbott", known_for: "Return of the Tokyo Woman"},
  {first_name: "Renaldo", last_name: "Homenick", known_for: "2201 A.D."},
  {first_name: "Janyce", last_name: "Kozey", known_for: "The Gypsy with a Thousand Faces"},
  {first_name: "Milton", last_name: "Lebsack", known_for: "The Tokyo City Who Fell to Earth"},
  {first_name: "Avis", last_name: "Johns", known_for: "The Dangerous Beast from Outer Space"},
  {first_name: "Kacie", last_name: "Moen", known_for: "Journey of the Red Dreams"},
  {first_name: "Teddy", last_name: "Bailey", known_for: "The Black Rose of Scotland"},
  {first_name: "Mickie", last_name: "Schuster", known_for: "Ultra Brains"},
  {first_name: "Felicitas", last_name: "Tromp", known_for: "The Black Rose of Wales"},
  {first_name: "Treasa", last_name: "Gusikowski", known_for: "The American Wizard"},
  {first_name: "Richard", last_name: "O'Keefe", known_for: "The Brain That Came to Dinner"},
  {first_name: "Wan", last_name: "Yundt", known_for: "Dangerous City"},
  {first_name: "Michell", last_name: "Frami", known_for: "Day of the American Blow"}
])
