Actor.create!([
  {first_name: "Nathan", last_name: "Fillion", known_for: "Firefly"},
  {first_name: "Sarah", last_name: "Michelle", known_for: "Buffy"},
  {first_name: "Allison", last_name: "Hannigan", known_for: "Buffy"},
  {first_name: "Robert", last_name: "Downey Jr.", known_for: "Iron Man"},
  {first_name: "Brad", last_name: "Pitt", known_for: "Fight Club"},
  {first_name: "Johnny", last_name: "Deep", known_for: "Pirates of the Caribean"},
  {first_name: "Will", last_name: "Smith", known_for: "Independence Day"},
  {first_name: "Samuel", last_name: "Jackson", known_for: "Pulp Fiction"},
  {first_name: "Christian", last_name: "Bale", known_for: "The Dark Knight"},
  {first_name: "Harrison", last_name: "Ford", known_for: "Indiana Jones"},
  {first_name: "Mark", last_name: "Hamill", known_for: "Star Wars"},
  {first_name: "Bruce", last_name: "Willis", known_for: "Die Hard"},
  {first_name: "Jason", last_name: "Bateman", known_for: "Arrested Development"},
  {first_name: "Will", last_name: "Arnett", known_for: "Bojack Horseman"},
  {first_name: "Amy", last_name: "Poehler", known_for: "Parks and Recreation"},
  {first_name: "Michael", last_name: "Cera", known_for: "Superbad"},
  {first_name: "Angelique", last_name: "Sporer", known_for: "Action Cousins"},
  {first_name: "Geralyn", last_name: "Corwin", known_for: "The Gypsy Who Fell to Earth"},
  {first_name: "Candance", last_name: "Shanahan", known_for: "The Action Thief from Outer Space"},
  {first_name: "Drew", last_name: "Armstrong", known_for: "The Cat Who Fell to Earth"},
  {first_name: "Deana", last_name: "Spinka", known_for: "A Fistful of Bloody Clash"},
  {first_name: "Mckinley", last_name: "Mann", known_for: "Blonde Rain: The Saul Rohan Story"},
  {first_name: "Marlyn", last_name: "Beatty", known_for: "Red Tears"},
  {first_name: "Gwenn", last_name: "Crona", known_for: "Fake Gypsy"},
  {first_name: "Nora", last_name: "Nikolaus", known_for: "The Ninjas with a Thousand Faces"},
  {first_name: "Treva", last_name: "Abbott", known_for: "Return of the Tokyo Woman"},
  {first_name: "Renaldo", last_name: "Homenick", known_for: "2201 A.D."},
  {first_name: "Janyce", last_name: "Kozey", known_for: "The Gypsy with a Thousand Faces"},
  {first_name: "Milton", last_name: "Lebsack", known_for: "The Tokyo City Who Fell to Earth"},
  {first_name: "Avis", last_name: "Johns", known_for: "The Dangerous Beast from Outer Space"},
  {first_name: "Kacie", last_name: "Moen", known_for: "Journey of the Red Dreams"},
  {first_name: "Teddy", last_name: "Bailey", known_for: "The Black Rose of Scotland"},
  {first_name: "Mickie", last_name: "Schuster", known_for: "Ultra Brains"},
  {first_name: "Felicitas", last_name: "Tromp", known_for: "The Black Rose of Wales"},
  {first_name: "Treasa", last_name: "Gusikowski", known_for: "The American Wizard"},
  {first_name: "Richard", last_name: "O'Keefe", known_for: "The Brain That Came to Dinner"},
  {first_name: "Wan", last_name: "Yundt", known_for: "Dangerous City"},
  {first_name: "Michell", last_name: "Frami", known_for: "Day of the American Blow"}
])
Movie.create!([
  {title: "War of the Man", year: 1989, plot: "Omnis enim dolores et voluptas molestiae voluptas. Eligendi et numquam occaecati quam soluta. Voluptas ad alias nesciunt qui velit quia quaerat."},
  {title: "The Tokyo Witch with a Thousand Faces", year: 1954, plot: "Optio ut esse dolores molestias nulla totam. Voluptatem dicta id quia sunt et. In beatae dicta nostrum aliquam."},
  {title: "Journey of the American Demon", year: 1976, plot: "Ut recusandae quae corporis laboriosam dolor quia. Officia fugiat repellat sequi unde ipsum. Iure qui earum eos est."},
  {title: "The Killer Hills with a Thousand Faces", year: 1952, plot: "Qui omnis ipsum aut error consequatur. Omnis qui blanditiis aut molestiae sit possimus quia assumenda. Enim enim veritatis eveniet nesciunt sint consequuntur. Est nobis veritatis quae doloribus dicta natus iure."},
  {title: "The Pickpocket Without a Ninja", year: 1943, plot: "Architecto sapiente blanditiis voluptate delectus tenetur et vitae molestiae. Quia et quae quibusdam cum error aut. Iusto voluptatem a deleniti deserunt est eaque ut consectetur. Ducimus necessitatibus aut quisquam minima."},
  {title: "The Green Beast from the Black Lagoon", year: 1939, plot: "Voluptates iste consequatur unde labore ut nobis. Error voluptas dolorum sequi nobis sed modi beatae. Omnis fuga molestiae qui et quod quam delectus aut."},
  {title: "The Fly with a Thousand Faces", year: 1992, plot: "Qui saepe aut commodi maxime qui odit reiciendis quia. Odio est ullam sunt maiores aliquam nulla et eos. Rerum saepe velit culpa at magni non. Eligendi vel dolorem illum harum enim. Voluptatum rerum facilis laboriosam eius."},
  {title: "Ultra Pickpocket", year: 2016, plot: "Dolor nam velit id facilis. Inventore ut fugiat magnam aut id libero. Consectetur nihil magnam cupiditate debitis qui quisquam aut. Debitis at adipisci sapiente eum officiis excepturi veritatis."},
  {title: "Red Cat", year: 1917, plot: "Facilis cumque saepe hic voluptas odit doloremque asperiores. Porro quos atque odit commodi fugiat ab. Repudiandae non qui id laboriosam et."},
  {title: "The Identity from Mars", year: 2019, plot: "Cupiditate placeat voluptate et accusamus consequatur eligendi. Iusto consequatur deleniti nihil id. Ipsum culpa non ducimus aut quis odit. Unde provident saepe harum blanditiis reiciendis."},
  {title: "Time of the Flying Rain", year: 1950, plot: "Doloremque aut voluptatibus rem quibusdam fuga. Et nihil asperiores ea labore modi. Occaecati commodi ipsum id enim dolorem."},
  {title: "Tokyo Men", year: 1964, plot: "Aperiam voluptatum ut et est et odit illum. Id et eligendi officia praesentium aut eos voluptas. Laborum et amet fugit at rem doloremque officiis illo. Voluptates eos ea suscipit ducimus error dolor."},
  {title: "Christmas on Gene Knoll", year: 2003, plot: "Officia in et repellendus adipisci error consequuntur. Velit ducimus et rerum et est. Temporibus sit eaque quia tempora aut et. Vel fugit illo laborum commodi. Enim et totam eveniet quae ad qui ipsam quos."},
  {title: "Time of the Diaries", year: 2016, plot: "At accusamus voluptatem inventore modi aut quisquam delectus. Ut officiis cum autem similique eveniet et. Vel doloribus temporibus modi quae pariatur. Eaque ipsum animi tempore quis facilis fuga. Expedita nulla est deserunt commodi."},
  {title: "Hungry Tentacle", year: 1901, plot: "Est atque at iste esse voluptatum. Cum explicabo officia sed fuga magni molestiae dolore culpa. Et veniam quos asperiores explicabo dolor ratione dolorum. Ut libero aperiam laborum aut velit nostrum ut occaecati. Laboriosam mollitia saepe temporibus ut sequi consequatur."},
  {title: "Danger Clash", year: 1917, plot: "Reiciendis numquam et fuga ut laborum consequatur et. Magnam ut corrupti eaque et sequi et occaecati. Sit temporibus quibusdam illum ad est atque vero cum."},
  {title: "Rise of the Fake Ninja", year: 1906, plot: "Est quis ipsa nulla molestias. Aut praesentium harum perspiciatis voluptatum. Magni repellat a sint nisi recusandae reiciendis animi. In sequi optio porro nobis odit id officiis. Quo nam quibusdam quod recusandae autem iure rerum tenetur."},
  {title: "Case of the Missing Cat", year: 1968, plot: "Ullam est aspernatur autem blanditiis cupiditate quasi quisquam alias. Natus magnam id quis ut consectetur. Distinctio illo qui possimus quae culpa est est. Optio architecto qui voluptatem dolor explicabo facere. Aspernatur deleniti dolor fugiat porro provident amet consequatur similique."},
  {title: "Killer World", year: 1912, plot: "Ipsa expedita necessitatibus perspiciatis maiores iusto fuga omnis. Fuga veniam magnam porro ut ducimus delectus et. Qui odio optio eum qui harum consequatur eos voluptatum."},
  {title: "Flying Jungle", year: 2007, plot: "Sit numquam eum fugit et ad quo. Harum omnis et quisquam et ex ipsam hic. Nostrum et nihil blanditiis consequatur."},
  {title: "Journey of the Nuclear Identity", year: 2018, plot: "Officia placeat et aut omnis ipsum ad qui et. Libero debitis qui qui molestiae. Ut unde dolor et fuga et tenetur a. Aut voluptate cum quae ut. Quia cupiditate tempora labore rem aut ipsam saepe odio."},
  {title: "The Hills from Hell", year: 1986, plot: "Illo asperiores similique et voluptas. Neque explicabo earum soluta ab dolorum quas eum. Necessitatibus magnam dolor tempora voluptas ut rem qui. Minus et voluptatem voluptas expedita nihil illo."},
  {title: "The Black Rose of Northern Ireland", year: 2005, plot: "Quia ipsa sit necessitatibus dolorum quo. Suscipit labore rem recusandae et voluptatem. Odit perspiciatis ipsa incidunt eaque velit iure. Temporibus quis enim omnis quaerat saepe autem tempora."},
  {title: "The Nuclear Wizard with a Thousand Faces", year: 1964, plot: "Aut omnis iure quae quidem vel. Pariatur corrupti temporibus eveniet quisquam. Qui inventore quis accusamus totam voluptas quod consequatur enim."},
  {title: "Hungry Thief", year: 1911, plot: "Et qui numquam voluptatum consequatur esse velit. Dolor rem facilis suscipit et distinctio rerum iste at. Consequatur quis iusto dicta pariatur. Aut illo dignissimos enim harum id deleniti ut."},
  {title: "War of the World", year: 1959, plot: "Velit possimus beatae sit suscipit consequuntur est. Sed blanditiis maxime vero maiores. Fuga aliquid eos dolor ea recusandae."},
  {title: "Day of the Identity", year: 2010, plot: "Et beatae minima sed quas asperiores labore cum quam. Ad magnam enim beatae id. Ab enim ad quia dolorum odit."},
  {title: "Bloody Witch 2: Son of Bloody Witch", year: 1973, plot: "Aperiam et et officiis necessitatibus quis repudiandae deleniti corrupti. Blanditiis et explicabo quisquam dignissimos. Id iusto voluptas voluptatem accusamus."},
  {title: "Christmas on Bobbye Estate", year: 2008, plot: "Assumenda id deserunt ut quasi. Enim asperiores veritatis hic aut. Culpa est unde molestiae qui praesentium."},
  {title: "The Action Wizard from Across the Ocean", year: 1957, plot: "Sunt vel cum itaque consequatur ut vitae. Modi dicta ipsam et tempore neque iure officia. Quo praesentium assumenda possimus voluptatum debitis cum et. Rerum sed consequuntur tempore et aliquam itaque pariatur."},
  {title: "The Killer Cat from Across the Ocean", year: 1927, plot: "Est expedita necessitatibus sit molestias id error. Ducimus architecto ut rerum quo quod ut tempora. Corrupti qui maxime vitae quod voluptatem magni omnis. Animi vero laboriosam eos aliquam dolorem."},
  {title: "The Fake Hills Who Fell to Earth", year: 1933, plot: "Illo laudantium autem magnam voluptatibus nemo. Vitae omnis laboriosam doloremque tempore qui qui debitis cupiditate. Ratione quasi ut asperiores et omnis. Beatae reprehenderit ut magni laborum. Sunt tenetur nam aut et vitae assumenda vel."},
  {title: "Blonde Cousins", year: 2004, plot: "Minima laboriosam modi distinctio ducimus aspernatur aut possimus et. Deleniti cumque et fuga quia. Aut nemo eaque et quo odit."},
  {title: "Christmas on Hintz Mount", year: 1932, plot: "Pariatur necessitatibus voluptatem autem omnis numquam et. Dolor iusto saepe mollitia quod vel nesciunt. Distinctio saepe dolor rerum iste."},
  {title: "The Wizard from the Black Lagoon", year: 2004, plot: "Ut qui enim aut in doloremque porro quia. Modi consequatur mollitia harum praesentium sit corporis voluptate. Ipsa perspiciatis libero aut debitis id quia velit. Et exercitationem aliquam quisquam laborum ut voluptatum aut. Rerum qui debitis optio eum corporis culpa laboriosam saepe."},
  {title: "I am Flying Identity", year: 2015, plot: "Ut aut earum fugiat sunt exercitationem voluptatem sit et. Amet voluptate vero ipsam labore porro. Et nihil ut cum quis rerum atque quod error."},
  {title: "Hungry Witch", year: 1971, plot: "Non illum fuga laboriosam nihil omnis. Iusto soluta laborum eum illum consequatur quia. Alias et necessitatibus fugiat fugit sint rerum omnis. Enim officia asperiores libero sunt officiis cupiditate."},
  {title: "The Ultra Beast", year: 1969, plot: "Explicabo dolorum molestias incidunt dolores. Rerum aliquid consequuntur provident est perferendis dolores aut. Quia voluptas asperiores facilis veniam nihil esse officia dicta. Aut eum quaerat nobis asperiores voluptatibus voluptas et."},
  {title: "Flying Diaries", year: 1932, plot: "Adipisci praesentium eum magni molestiae fugit eveniet. Sed architecto ut consequatur excepturi in tempora assumenda et. Aliquam tempore et dolor suscipit eveniet. Ex voluptas asperiores labore aut quis aut dolore. Quis sit rerum velit aut."},
  {title: "Legend of Dangerous Mutant", year: 1915, plot: "Voluptatem labore sit officia nulla quaerat similique. Repellat qui distinctio a et. Tempore molestiae aut labore voluptatem. Numquam rerum aut qui beatae fuga quia et. Ea libero repellat sapiente ducimus rerum quaerat est beatae."},
  {title: "Dr. Diaries", year: 2007, plot: "Quo error qui esse quam quas sit saepe delectus. Eveniet dolores et necessitatibus sequi labore. Beatae repellendus rerum iusto nisi illo repellat eveniet. Sed dolor cumque et illum minima. Praesentium in dolor eos quasi est."},
  {title: "Bloody Tears", year: 1995, plot: "Necessitatibus accusamus quia est beatae illum. Officia rerum sed quas omnis. Exercitationem odit sed magni labore atque vitae. Asperiores quod possimus ipsum aut illo. Voluptatem velit voluptas minima non dolores enim."},
  {title: "Nuclear Women", year: 1961, plot: "Est vel sint numquam eveniet tenetur aspernatur. Reiciendis suscipit dolor in laudantium natus a ullam. Quam harum veniam nobis voluptas. Quo sit quaerat nostrum repellat ipsa non accusamus rem. Quos est et esse quis."},
  {title: "253 A.D.", year: 1960, plot: "Et minima aut sed minus facilis et. Fugiat est et velit maiores enim possimus. Animi dolor repellendus odit ipsa magnam. Dolore nihil fugit maxime sint."},
  {title: "The Wizard from Across the Ocean", year: 1961, plot: "A voluptatem deserunt consequatur assumenda. Necessitatibus qui dolores asperiores quis. Vitae rerum enim nemo voluptas quasi aliquid. Optio enim minima facilis expedita exercitationem dolor. Impedit aliquam dicta est error omnis."},
  {title: "Christmas on Beatris Plaza", year: 2019, plot: "Ducimus dolor pariatur dolores consequatur similique harum. Est fugiat sunt quisquam eaque. Quam et sit quos voluptatem dolorem consequatur. Voluptate quis ut beatae sint voluptatum. Vel at magni perspiciatis consequatur eum deleniti unde quia."},
  {title: "Danger Man", year: 2017, plot: "Et minus ea corporis nemo ipsa vel et. Dolor mollitia fugiat temporibus odit nihil. Ad dicta autem necessitatibus possimus reiciendis amet non tempore. Porro totam consectetur quo esse vel quis aperiam consequatur."},
  {title: "The Death Cousins That Came to Dinner", year: 2010, plot: "Quam ut reiciendis ullam sed consequatur voluptatem quis nesciunt. Adipisci molestiae sint est fugit culpa ut. Consequuntur ab ullam qui veritatis. Officiis distinctio odio quo eveniet aut laborum dolore rerum. Autem et ut ducimus vel."},
  {title: "Season of the Fake Wizard", year: 1915, plot: "Nihil dignissimos iusto eligendi recusandae est. Quibusdam pariatur quo deserunt dolore repellat. Quo et rerum sit quam sequi."},
  {title: "Season of the Blonde Monster", year: 1946, plot: "Molestias est optio dignissimos dolore ab facilis eligendi eum. Natus quam laboriosam praesentium inventore corrupti. Accusamus iusto totam sapiente fugit. In ut sint provident laboriosam perspiciatis aut debitis. Ut expedita nam adipisci sed ut officiis."}
])
